name: extended_nested_scroll_view
description: extended nested scroll view to fix pinned header and inner scrollables sync issues.
version: 6.0.0
homepage: https://github.com/fluttercandies/extended_nested_scroll_view

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.3.3 

  scroll_to_index: ^3.0.1


